local CHATBOX = CORE.CHATBOX

CHATBOX.Sounds = {}

function CHATBOX:AddSound( word, vid, stop, start, volume )
	CHATBOX.Sounds[word] = { url = vid, stop = stop or time, start = start or 0, volume = volume or 80}
end
CHATBOX:AddSound("who the fuck is this asshole", "5KzuP_KNPLs", 3, 0)
CHATBOX:AddSound("i did not hit her", "biKt7vySKxs", 5, 0, 75)
CHATBOX:AddSound("shut the fuck up", "nc_LIR5ExIU", 4, 0, 50)
CHATBOX:AddSound("stfu", "nc_LIR5ExIU", 4, 0, 50)
CHATBOX:AddSound("have you tried", "p85xwZ_OLX0", 9, 0, 75)
CHATBOX:AddSound("yeah bitch", "IoHUy3uxV8g", 3)
CHATBOX:AddSound("gatorade me bitch", "v3T9eyaIBi8", 5)
CHATBOX:AddSound("carl that kills", "wwGsZZN-YD4", 9)
CHATBOX:AddSound("say what again", "RtXF2j5JAds", 10)
CHATBOX:AddSound("bullshit", "sWs0D5EhKUs", 2)
CHATBOX:AddSound("i love you fuck off", "76nNHbX0lO4", 10)
CHATBOX:AddSound("get to the chopper", "-9-Te-DPbSE", 7, 0, 75)
CHATBOX:AddSound("im back", "3pK3d2Pk0Zk", 2)
CHATBOX:AddSound("ill be back", "bgLfOrVJJMg", 4)
CHATBOX:AddSound("frankly my dear", "PAqxWa9Rbe0", 4)
CHATBOX:AddSound("bond james bond", "raplvZFysjU", 3)
CHATBOX:AddSound("failure to communicate", "V2f-MZ2HRHQ", 10, 0, 75)
CHATBOX:AddSound("do you feel lucky", "A732Cuuo2tI", 14)
CHATBOX:AddSound("youre a madman", "9QdY4gfR7iY", 4, 3)
CHATBOX:AddSound("shut up and fuck me", "_86NPOY7mMI", 4, 99)
CHATBOX:AddSound("an offer he cant refuse", "SeldwfOwuL8", 4, 12)
CHATBOX:AddSound("make my day", "mevxenJ6Mtc", 4, 3)
CHATBOX:AddSound("fuck you", "eZGbUigdWS0", 4, 53)
CHATBOX:AddSound("i never asked for this", "CXpuRIZzJog", 3)
CHATBOX:AddSound("youre tearing me apart", "Plz-bhcHryc", 3, 3)
CHATBOX:AddSound("enough is enough", "PZ2QFmJ7h0A", 3)
CHATBOX:AddSound("did you see that ludicrous display last night", "6yN2H3--1aw", 17, 1)
CHATBOX:AddSound("show me the money", "FFrag8ll85w", 3, 85)
CHATBOX:AddSound("im walking here", "c412hqucHKw", 7, 16)
CHATBOX:AddSound("mother fucker", "86csBSS4WHk", 3, 15)
CHATBOX:AddSound("funny looking fucker", "oLGQd2xv2KI", 3, 142)
CHATBOX:AddSound("hey baby", "EwIEUflY6YI", 3, 45)
CHATBOX:AddSound("me so horny", "EwIEUflY6YI", 2, 54)
CHATBOX:AddSound("me love you long time", "EwIEUflY6YI", 3, 73)
CHATBOX:AddSound("me sucky sucky", "EwIEUflY6YI", 2, 82)
CHATBOX:AddSound("what do we get for 10 dollars", "EwIEUflY6YI", 10, 94)
CHATBOX:AddSound("actually mr jensen", "iHj5je8Ru00", 12, 118)
CHATBOX:AddSound("brown bear", "YexQcXnVSzg", 6, 5, 20)
CHATBOX:AddSound("i love you", "ceTgUezZIc0", 3, 79)
CHATBOX:AddSound("oh shit im sorry", "BuoaGPlWr-4", 3, 3)
CHATBOX:AddSound("sorry for what", "BuoaGPlWr-4", 3, 5)
CHATBOX:AddSound("im sorry dave", "ARJ8cAGm6JE", 4, 64)
CHATBOX:AddSound("only steers and queers come from texas", "vyFSdj1J5Vw", 6, 3)
CHATBOX:AddSound("make like a tree", "nX79DrHzfKE", 3)
CHATBOX:AddSound("dont you have some offs to fuck", "z5pAS-nxmAE", 3, 32)
CHATBOX:AddSound("its over 9000", "SiMHTK15Pik", 3, 10)
CHATBOX:AddSound("youre moms a milf", "OdXry79EifM", 4, 5)
CHATBOX:AddSound("i cry when angels deserve to die", "ZoSpBy2Itsk", 11, 76, 20)
CHATBOX:AddSound("lana", "wSGU4ND_v_E", 8, 0, 100)
CHATBOX:AddSound("how about no", "2HJxya0CWco", 4, 6)
CHATBOX:AddSound("do you understand", "-twUCEfzrDk", 5, 6, 50)
CHATBOX:AddSound("allah akbar", "lo8K63FHDOs", 3, 6, 5)
CHATBOX:AddSound("check your privilege", "i0C3IhWcJH0", 5, 34, 65)
CHATBOX:AddSound("hey over here", "V2ZAe1qTBC4", 3, 4)
CHATBOX:AddSound("i did not have sexual relations with that woman", "VBe_guezGGc", 5, 17, 60)
CHATBOX:AddSound("fool me once", "eKgPY1adc0A", 13, 4, 60)
CHATBOX:AddSound("fuck her right in the pussy", "6w1DsOA-1pM", 3, 9, 75)
CHATBOX:AddSound("yeah well fuck", "uAO4YHBpPyU", 7, 167, 75)
CHATBOX:AddSound("straya", "rMdbVHPmCW0", 7, 0, 25)
CHATBOX:AddSound("around the world", "DLpEOdDW1-k", 4, 57, 25)
CHATBOX:AddSound("who threw that", "Ow0xZG9XZ5w", 10, 138, 100)
CHATBOX:AddSound("gotta get jiggy with it", "3JcmQONgXJM", 4, 26, 100)
CHATBOX:AddSound("you will soon have your god", "1b-bijO3uEw" , 6, 160, 100)
CHATBOX:AddSound("top kek", "6hcSpSC8T0M", 6, 0, 50)
CHATBOX:AddSound("all star", "L_jWHffIx5E", 3, 74, 20)
CHATBOX:AddSound("mario death", "ZtHsWV2t2kY", 5, 0, 20)
CHATBOX:AddSound("fatality", "-Fykb-V-2oM", 3, 0, 10)
CHATBOX:AddSound("i cant go for that","ErkH4K39UrI", 4, 40, 10)
CHATBOX:AddSound("fegelein","nvswCuHbPvs",7 ,30, 50)
CHATBOX:AddSound("ciggy butt brain", "vmL72sgVdAQ", 2, 49, 50)
CHATBOX:AddSound("you dopey cunt", "vmL72sgVdAQ", 3, 75, 50)
CHATBOX:AddSound("who the fuck said that", "3cRwIqTe4AE", 14, 0, 100)
CHATBOX:AddSound("i cant take the shot", "s0hsmTp608U", 10, 39, 80)
CHATBOX:AddSound("we going with damo", "3HKW1YxQ8nc", 3, 8, 80)
CHATBOX:AddSound("take a fuck load of mdma", "QTYID4lXhM0", 3, 5, 80)
CHATBOX:AddSound("i need an adult", "kscG_gs2BOc", 4, 6, 80)
CHATBOX:AddSound("insane in the membrane", "zAlNrtcPCLw", 4, 52, 60)
CHATBOX:AddSound("fuck yeah bud", "F-glHAzXi_M", 3, 71, 60)
CHATBOX:AddSound("just out for a rip", "F-glHAzXi_M", 4, 74, 60)
CHATBOX:AddSound("i knew you were trouble", "vNoKguSdy4Y", 5, 163, 60)
CHATBOX:AddSound("shake it off", "nfWlot6h_JM", 5, 60, 20)
CHATBOX:AddSound("all about that bass", "7PCkvCPvDXk", 5, 0, 60)
CHATBOX:AddSound("why you gotta be so rude", "PIh2xe4jnpk", 4, 41, 20)
CHATBOX:AddSound("bbz will u luv me 4evr", "CQuR8LVKhUE", 3, 9, 20)
CHATBOX:AddSound("rick roll", "dQw4w9WgXcQ", 12, 18, 20)
CHATBOX:AddSound("lamar", "WrrYDH9Dv9g", 4, 36, 70)
CHATBOX:AddSound("merica fuck yeah", "IhnUgAaea4M", 4, 14, 40)
CHATBOX:AddSound("i live for the applause", "QFIOoZy9Hm8", 4, 41, 40)
CHATBOX:AddSound("never give up", "KxGRhd_iWuE", 4, 30, 50)
CHATBOX:AddSound("just do it", "nuHfVn_cfHU", 4, 5, 50)

function CHATBOX:PlaySound( word )
	if CHATBOX.Sounds[word] then
		local tbl = CHATBOX.Sounds[word]
		
		local dframe = vgui.Create("DFrame")
		dframe:SetSize(1, 1)
		dframe:SetPos(-2,-2)
		dframe:SetTitle("")
		
		local dhtml = vgui.Create("DHTML", dframe)
		dhtml:SetPos(0, 0)
		dhtml:SetSize(1,1)
		dhtml:SetScrollbars(false)
		dhtml:SetAllowLua(false)
		dhtml.ConsoleMessage = function() end
		dhtml:OpenURL("http://127.0.0.1/yt.php?vid=" .. tbl.url .. "&start=" .. tbl.start .. "&vol=" .. tbl.volume)
		//dhtml:OpenURL("https://www.youtube.com/watch?v=" .. tbl.url .. "?t=" .. tbl.start)
		
		timer.Simple(CHATBOX.Sounds[word].stop + 1, function()
			dframe:Close()
		end)
	end
end
